name: local-dev
services:
  app:
    build:
      context: ../
      dockerfile: build/docker/app/Dockerfile
      target: development
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - db
      - cache
    environment:
      - API_PORT=${API_PORT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}

  db:
    image: postgres:17.0-alpine
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate:v4.18.1
    profiles: ["tools"]
    volumes:
      - ../migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database",
        "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable",
      ]
    command: ["up"]
    restart: on-failure

  cache:
    image: redis:7.4.1-alpine
    restart: always
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command:
      - redis-server
    volumes:
      - redis_data:/data

volumes:
  db_data:
  redis_data: